### ISSUE TITLE
[OpenSCAD 2015.03-2] PolyGear.scad "ERROR: Parser error in line 129: syntax error  ERROR: Compilation failed!"

### ISSUE THREAD

**Issue by ajrio** [dpellegr/PolyGear#1]
Using OpenSCAD version 2015.03-2.  Seems to traceback to line 118 in PolyGearUtils.scad from the includes and doesn't seem to like "let(p=pts[i])" syntactically.

**Comment by dpellegr** [comment]
Gosh, that's an OLD version, I had not even heard about OpenSCAD at the time! Is there any reason for sticking to that? Updating to v2019.05 would solve the issue with no effort.

**Comment by ajrio** [comment]
You're right. Updating fixed it.  Thanks. (And nice work)
