### ISSUE TITLE
Planetary flip!

### ISSUE THREAD

**Issue by MrBenGriffin** [dpellegr/PolyGear#11]
Loving this work.

In your "planetary.scad" demo on line 27 you should flip the sun - otherwise the profiling will fail.
I think it would be more useful to others to add your herringbone() function to this example also.
It's a beautiful thing. 

Rx(180) Rz(180/sun_teeth*((planet_teeth+1)%2)) spur_gear(n=sun_teeth, z=10);

Here I am using a flattened spur gear to turn the ring into a thumb ring.  
![image](https://github.com/dpellegr/PolyGear/assets/1785064/5534d5b8-b9a1-4756-8171-43c8b17a3433)

This is a really awesome repository, which would really do with some more documentation - mainly on how to set profiles, and use linespace for those who are not familiar with it.  Your notes are good - but buried.  The inclusion of the academic texts (for terminology) is very useful, but, while explains the 'why' - it doesn't so much explain the how!
Also, even a tutorial for building up a gear chain would be awesome.

**Comment by dpellegr** [comment]
Hello @MrBenGriffin thank you for your comment.
I see what you mean. There are several options to do that: you can rotate or mirror the resulting sun but also flip the sign of the helix_angle. I did not need to do either as in the example the teeth have zero helicity.

Concerning the documentation, apart from the readme, I tried to make the library files as accessible as possible as I believe that it is always better to peek at the sources to access the full capabilities of a peace of code.

Regarding the how, there are two main steps:
1. computing the surface points -> the procedure closely follows what explained in the papers
2. triangulating them into surfaces and solids -> actually not too conceptually difficult, but one must be careful keeping the points  and the faces well organized.

But yeah, I understand your feelings: it is not a simple library to dig into, that's the price to pay for its ultra high performances.
