### ISSUE TITLE
bevel gear pair dimensions

### ISSUE THREAD

**Issue by Jaroslav-Krch** [dpellegr/PolyGear#3]
Hi, I love the poly gear especially the bevel gears pair. I have no clue how did you do it, but it is briliant :-)

But I am missing functions to get the bevel gears dimensions to be able to integrate them. Like outer/inner diameters, any z value of the gear bottom surface and the thickness. Distance of gear center at the bottom surface to the [0,0]. 

For now I am best guessing them (do not like it, but not smart enough). Thanks.

**Comment by dpellegr** [comment]
Hi and thank you for your interest.
I have updated the readme, including much more guidance/documentation.
Please let me know if you have further questions.

**Comment by Jaroslav-Krch** [comment]
Thank you for the update and the references.

**Comment by dpellegr** [comment]
Thanks to you for asking clarifications.
For every person that does that, there are probably tens which just give up, without giving me a chance to improve my work.

I expanded the readme a bit more, I hope it helps.

I am closing the issue for now, if something is not clear please do not hesitate to reopen/continuing on this issue.
