### ISSUE TITLE
Expose the tooth profile generator

### ISSUE THREAD

**Issue by ReallyCoolName** [dpellegr/PolyGear#4]
Personally, there are things I'd like to be able to control (for example, intentionally leaving "bald spots" on the gear). To that end, the ability to place the teeth yourself would be nice.

I tried following the code a bit, but it wasn't easy for me to find, perhaps because my lack of experience.

And also, thank you for this!

**Comment by dpellegr** [comment]
The relevant code is in PolyGearBasics.scad (which has been coded after the paper in the doc folder), but for performance reasons those are all functions, spitting out numbers and not polygons or polyhedrons. So you have to build the shapes that you need by picking the right lists of points, which is what the rest of the library does.

However if you are just after your example, it would be pretty straightforward to use boolean operations to fill or take away teeth. For instance intersecting a gear with a circular sector will give you just a few teeth that you can then union with a cylinder.

**Comment by ReallyCoolName** [comment]
> 
> 
> The relevant code is in PolyGearBasics.scad (which has been coded after the paper in the doc folder), but for performance reasons those are all functions, spitting out numbers and not polygons or polyhedrons. So you have to build the shapes that you need by picking the right lists of points, which is what the rest of the library does.
> 
> However if you are just after your example, it would be pretty straightforward to use boolean operations to fill or take away teeth. For instance intersecting a gear with a circular sector will give you just a few teeth that you can then union with a cylinder.

Thanks! that's what I ended up doing so far. I'll have a look, I'd like to understand the code anyway. I suppose since picking the right list is a whole thing in and of itself, it's a moot issue? guess I'll close :P
