### ISSUE TITLE
bug on helix_angle and 90 degrees axis_angle

### ISSUE THREAD

**Issue by dfelippa** [dpellegr/PolyGear#9]
Dear Mr. Pellegrini

Thank you very much for creating and making PolyGear available to all. I'm very grateful

I would like to report a bug. I tried to fix it but am not proficient enough.

The bug is as follows:

On a bevel gear when using 90 degrees axis_angle and a different gear size ratio the generated gears have inconsistent design and do not match.
It becomes more evident when the difference between the number of teeth is large.

For an instance, for:

  bevel_pair(w=5, n1=60, n2=6, only=0, axis_angle=90, helix_angle = zerol(60));

the pinon has a far steeper curvature then the gear

Could you please fix it?

Thank you very much,
Dennis

This is the image:
![badgear](https://user-images.githubusercontent.com/7536886/157685922-177cc7b2-3e16-4826-b1b6-73a2a5996df7.png)

**Comment by dpellegr** [comment]
Nice catch and thank you for reporting!

I have already located the issue (I think), but I need some time to implement a solution... stay tuned.

**Comment by dpellegr** [comment]
Fixed by https://github.com/dpellegr/PolyGear/commit/777a04649aca37ef864eec8fa69a5047320f940f

![Untitled](https://user-images.githubusercontent.com/7815854/158069250-9c88c29f-d9ec-46b0-b64d-e7af00ea0e9b.png)

**Comment by dfelippa** [comment]
Thank you very much
